update docker but not finished

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,34 +1,37 @@
-FROM node:16.13.0 AS base
-RUN apt-get update && apt-get install libssl-dev ca-certificates -y
+FROM node:16-alpine AS base
+
+FROM base AS deps
+
 WORKDIR /app
 
-COPY package.json yarn.lock ./
+COPY package.json yarn.lock  ./
+RUN \
+    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
 
-FROM base AS build
-# ENV NODE_ENV=production
 
-RUN yarn
-
+FROM base AS builder
+WORKDIR /app
+ENV NEXT_PUBLIC_API_URL=/api
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-RUN yarn run prisma:generate
+
 RUN yarn build
 
-FROM base as prod-build
+FROM base AS runner
+WORKDIR /app
+ENV NODE_ENV production
 
-RUN yarn install --production
-COPY prisma prisma
-RUN yarn run prisma:generate
-RUN cp -R node_modules prod_node_modules
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 
-FROM base as prod
+COPY --from=builder /app/public ./public
 
-COPY --from=prod-build /app/prod_node_modules /app/node_modules
-COPY --from=build  /app/.next /app/.next
-COPY --from=build  /app/public /app/public
-COPY --from=build  /app/prisma /app/prisma
-COPY --from=build  /app/scripts /app/scripts
 
-EXPOSE 80
-# CMD ["yarn", "start"]
-CMD ["bash", "scripts/run_server.sh"]
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+
+USER nextjs
 
